// seedUsers.js

export const seedUsers = [
  // ------------------ [남성 유저 10명] ------------------
  {
    userId: "user_m01",
    name: "김민준",
    gender: "male",
    preferredGender: ["male"],
    age: 23,
    ageMin: 20,
    ageMax: 26,
    preferredDistricts: ["성북구", "동대문구", "종로구"],
    rentRange: [40, 50], // 희망 월세 범위 (최저 40만 ~ 최대 50만 원)
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [23, 25],
    noiseLevel: 2,
    socialLevel: 4,
    stayDuration: 12,
    intro: "고려대 재학 중입니다! 밤에 조용히 잘 자는 성향이고 규칙적인 라이프스타일을 선호해요."
  },
  {
    userId: "user_m02",
    name: "박지성",
    gender: "male",
    preferredGender: ["male"],
    age: 24,
    ageMin: 22,
    ageMax: 28,
    preferredDistricts: ["성북구", "강북구", "동대문구"],
    rentRange: [45, 60],
    isSmoking: false,
    smokingTolerance: 3,
    sleepRange: [24, 26],
    noiseLevel: 3,
    socialLevel: 5,
    stayDuration: 24,
    intro: "친하게 지낼 룸메 구합니다! 주말에 같이 맛집 탐방 다니는 거 좋아해요."
  },
  {
    userId: "user_m03",
    name: "이현우",
    gender: "male",
    preferredGender: ["male"],
    age: 21,
    ageMin: 20,
    ageMax: 24,
    preferredDistricts: ["성북구", "종로구", "중구"],
    rentRange: [35, 45],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [22, 24],
    noiseLevel: 1,
    socialLevel: 1,
    stayDuration: 12,
    intro: "컴퓨터공학과 학생입니다. 각자 개인 생활 존중하면서 조용히 지내는 걸 좋아합니다."
  },
  {
    userId: "user_m04",
    name: "정우진",
    gender: "male",
    preferredGender: ["male"],
    age: 25,
    ageMin: 23,
    ageMax: 29,
    preferredDistricts: ["동대문구", "성북구", "중랑구"],
    rentRange: [45, 55],
    isSmoking: true,
    smokingTolerance: 4,
    sleepRange: [23, 25],
    noiseLevel: 3,
    socialLevel: 3,
    stayDuration: 6,
    intro: "취준생입니다. 깔끔하게 유지하는 편이고 흡연은 베란다/외부에서만 합니다."
  },
  {
    userId: "user_m05",
    name: "최도현",
    gender: "male",
    preferredGender: ["male"],
    age: 22,
    ageMin: 20,
    ageMax: 25,
    preferredDistricts: ["성북구", "동대문구", "노원구"],
    rentRange: [30, 40],
    isSmoking: false,
    smokingTolerance: 2,
    sleepRange: [25, 27],
    noiseLevel: 4,
    socialLevel: 4,
    stayDuration: 12,
    intro: "음악 작업 일을 하고 있어서 밤 늦게 자는 편입니다. 쾌활한 성격이에요!"
  },
  {
    userId: "user_m06",
    name: "강태양",
    gender: "male",
    preferredGender: ["male"],
    age: 26,
    ageMin: 24,
    ageMax: 30,
    preferredDistricts: ["종로구", "중구", "용산구"],
    rentRange: [50, 70],
    isSmoking: false,
    smokingTolerance: 1,
    sleepRange: [23, 24],
    noiseLevel: 2,
    socialLevel: 3,
    stayDuration: 24,
    intro: "직장인입니다. 주말에는 고향 내려가서 집 비우는 날이 많습니다."
  },
  {
    userId: "user_m07",
    name: "윤시우",
    gender: "male",
    preferredGender: ["male"],
    age: 23,
    ageMin: 21,
    ageMax: 25,
    preferredDistricts: ["성북구", "종로구", "동대문구"],
    rentRange: [40, 50],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [23, 25],
    noiseLevel: 2,
    socialLevel: 3,
    stayDuration: 12,
    intro: "국민대 재학 중입니다. 청소 분리수거 루틴 확실히 지킵니다."
  },
  {
    userId: "user_m08",
    name: "한승현",
    gender: "male",
    preferredGender: ["male"],
    age: 24,
    ageMin: 20,
    ageMax: 27,
    preferredDistricts: ["성북구", "강북구", "도봉구"],
    rentRange: [35, 45],
    isSmoking: false,
    smokingTolerance: 2,
    sleepRange: [24, 25],
    noiseLevel: 3,
    socialLevel: 2,
    stayDuration: 6,
    intro: "단기 거주 희망합니다. 서로 선 지키며 편하게 지내요!"
  },
  {
    userId: "user_m09",
    name: "임건우",
    gender: "male",
    preferredGender: ["male"],
    age: 20,
    ageMin: 20,
    ageMax: 24,
    preferredDistricts: ["성북구", "동대문구", "성동구"],
    rentRange: [40, 50],
    isSmoking: false,
    smokingTolerance: 1,
    sleepRange: [23, 25],
    noiseLevel: 1,
    socialLevel: 4,
    stayDuration: 12,
    intro: "새내기 학생입니다! 룸메 형들과 친하게 지내고 싶습니다."
  },
  {
    userId: "user_m10",
    name: "오성진",
    gender: "male",
    preferredGender: ["male"],
    age: 27,
    ageMin: 24,
    ageMax: 31,
    preferredDistricts: ["성북구", "동대문구", "종로구"],
    rentRange: [50, 65],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [22, 24],
    noiseLevel: 2,
    socialLevel: 1,
    stayDuration: 24,
    intro: "대학원생입니다. 집에서는 거의 수면과 휴식만 취합니다."
  },

  // ------------------ [여성 유저 10명] ------------------
  {
    userId: "user_f01",
    name: "이서연",
    gender: "female",
    preferredGender: ["female"],
    age: 22,
    ageMin: 20,
    ageMax: 25,
    preferredDistricts: ["성북구", "강북구", "마포구"],
    rentRange: [35, 45],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [25, 27],
    noiseLevel: 4,
    socialLevel: 2,
    stayDuration: 6,
    intro: "성신여대 미대생입니다. 과제가 많아 조금 늦게 자는 편이에요!"
  },
  {
    userId: "user_f02",
    name: "김지유",
    gender: "female",
    preferredGender: ["female"],
    age: 23,
    ageMin: 21,
    ageMax: 26,
    preferredDistricts: ["성북구", "동대문구", "종로구"],
    rentRange: [45, 55],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [23, 25],
    noiseLevel: 2,
    socialLevel: 4,
    stayDuration: 12,
    intro: "고려대 사범대 다니고 있습니다. 주말엔 같이 홈카페 즐겨요!"
  },
  {
    userId: "user_f03",
    name: "박하은",
    gender: "female",
    preferredGender: ["female"],
    age: 21,
    ageMin: 20,
    ageMax: 23,
    preferredDistricts: ["성북구", "종로구", "서대문구"],
    rentRange: [40, 50],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [22, 24],
    noiseLevel: 1,
    socialLevel: 3,
    stayDuration: 12,
    intro: "한성대 재학 중입니다. 예민한 편이라 서로 조용히 배려하는 환경이 좋아요."
  },
  {
    userId: "user_f04",
    name: "최수아",
    gender: "female",
    preferredGender: ["female"],
    age: 24,
    ageMin: 22,
    ageMax: 28,
    preferredDistricts: ["성북구", "동대문구", "강북구"],
    rentRange: [45, 60],
    isSmoking: true,
    smokingTolerance: 3,
    sleepRange: [24, 26],
    noiseLevel: 3,
    socialLevel: 5,
    stayDuration: 24,
    intro: "성격 시원시원합니다! 요리하는 것 좋아해서 밥 같이 먹는 거 환영해요."
  },
  {
    userId: "user_f05",
    name: "윤다은",
    gender: "female",
    preferredGender: ["female"],
    age: 25,
    ageMin: 23,
    ageMax: 27,
    preferredDistricts: ["마포구", "서대문구", "관악구"],
    rentRange: [50, 65],
    isSmoking: false,
    smokingTolerance: 1,
    sleepRange: [23, 24],
    noiseLevel: 2,
    socialLevel: 3,
    stayDuration: 12,
    intro: "신촌 쪽으로 취업해서 이사 준비 중인 사회초년생입니다."
  },
  {
    userId: "user_f06",
    name: "장민서",
    gender: "female",
    preferredGender: ["female"],
    age: 22,
    ageMin: 20,
    ageMax: 24,
    preferredDistricts: ["성북구", "동대문구", "종로구"],
    rentRange: [40, 50],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [23, 25],
    noiseLevel: 2,
    socialLevel: 4,
    stayDuration: 12,
    intro: "서경대 다니고 있어요. 밤에 조용히 잠 잘 자고 감정 기복 없는 편입니다!"
  },
  {
    userId: "user_f07",
    name: "조예린",
    gender: "female",
    preferredGender: ["female"],
    age: 20,
    ageMin: 20,
    ageMax: 22,
    preferredDistricts: ["성북구", "강북구", "노원구"],
    rentRange: [30, 40],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [24, 25],
    noiseLevel: 3,
    socialLevel: 3,
    stayDuration: 3,
    intro: "계절학기 및 인턴 기간 동안 3개월 정도 짧게 살 룸메이트 구합니다."
  },
  {
    userId: "user_f08",
    name: "신유진",
    gender: "female",
    preferredGender: ["female"],
    age: 23,
    ageMin: 22,
    ageMax: 26,
    preferredDistricts: ["성북구", "종로구", "동대문구"],
    rentRange: [35, 45],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [22, 24],
    noiseLevel: 1,
    socialLevel: 1,
    stayDuration: 24,
    intro: "시험 준비 중인 고시생입니다. 개인 시간 완전 보장 원합니다."
  },
  {
    userId: "user_f09",
    name: "한소희",
    gender: "female",
    preferredGender: ["female"],
    age: 26,
    ageMin: 23,
    ageMax: 29,
    preferredDistricts: ["성북구", "동대문구", "중랑구"],
    rentRange: [50, 70],
    isSmoking: false,
    smokingTolerance: 2,
    sleepRange: [23, 25],
    noiseLevel: 2,
    socialLevel: 4,
    stayDuration: 12,
    intro: "직장인입니다. 퇴근 후 같이 맥주 한잔하며 수다 떨 수 있으면 좋겠어요!"
  },
  {
    userId: "user_f10",
    name: "배채원",
    gender: "female",
    preferredGender: ["female"],
    age: 22,
    ageMin: 20,
    ageMax: 24,
    preferredDistricts: ["성북구", "종로구", "강북구"],
    rentRange: [40, 50],
    isSmoking: false,
    smokingTolerance: 0,
    sleepRange: [25, 26],
    noiseLevel: 3,
    socialLevel: 2,
    stayDuration: 12,
    intro: "휴학생입니다. 집에서는 조용히 영화 보거나 인테리어 가꾸는 거 좋아해요."
  }
];